name = "carabiner-schema"
main = "src/worker.ts"
compatibility_date = "2024-12-25"

[env.production]
route = { pattern = "carabiner.outfitter.dev/*", zone_name = "outfitter.dev" }

[[kv_namespaces]]
binding = "SCHEMA_STORE"
id = "YOUR_KV_NAMESPACE_ID" # Replace with actual KV namespace ID

[site]
bucket = "./public"